version: '3'
services:
  development-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/development-env:prod
    volumes:
      - dev-env-home:/home
    container_name: development-env
    environment:
      - TZ=America/Denver
    ports:
      - 8000:3000
      - 8001:8787
    privileged: true
    restart: unless-stopped
    
volumes:
  dev-env-home:
    driver: local