version: '3'
services:
  development-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/development-env:dev
    volumes:
      - dev-env-home:/home
    container_name: development-env
    environment:
      - TZ=America/Denver
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2GB
    ports:
      - 8000:8787
      - 8001:8888
    privileged: true
    restart: unless-stopped
    
volumes:
  dev-env-home:
    driver: local